[workspace]
members = [
    "crates/agent",
    "crates/protocol",
    "crates/server",
]

[workspace.dependencies]
anyhow = "1.0"
log = "0.4"
env_logger = "0.10"
serde = { version = "^1.0.152", features = ["derive"] }
uuid = { version = "^1.0.0", features = ["v4", "serde"] }
serde_json = "1.0"
