# .github/workflows/release.yml

on:
  push:
    branches:
      - 'main'

jobs:
  release:
    name: release ${{ matrix.src_dir }} for ${{ matrix.target }}
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        target: [x86_64-pc-windows-gnu, x86_64-unknown-linux-musl, x86_64-apple-darwin]
        src_dir: [agent, server]
        include:
          - target: x86_64-pc-windows-gnu
            archive: zip
          - target: x86_64-unknown-linux-musl
            archive: tar.gz
          - src_dir: agent
            extra: sample/agent/config.json
          - src_dir: server
            extra: sample/server/config.json
    steps:
      - uses: actions/checkout@master
      - name: Compile and release
        id: compile
        uses: rust-build/rust-build.action@v1.4.0
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          RUSTTARGET: ${{ matrix.target }}
          ARCHIVE_TYPES: ${{ matrix.archive }}
          SRC_DIR: crates/${{ matrix.src_dir }}
          EXTRA_FILES: ${{ matrix.extra }}
          UPLOAD_MODE: none
          TOOLCHAIN_VERSION: stable
      - name: Upload artifact
        uses: actions/upload-artifact@v3
        with:
          name: ${{ matrix.src_dir }}-${{ matrix.target }}
          path: ${{ steps.compile.outputs.BUILT_ARCHIVE }}
      - name: Upload artifact
        uses: actions/upload-artifact@v3
        with:
          name: ${{ matrix.src_dir }}-${{ matrix.target }}.sha256sum
          path: ${{ steps.compile.outputs.BUILT_CHECKSUM }}
